# Configuration file for terraform-docs
# See https://terraform-docs.io/user-guide/configuration/ for more information

formatter: "markdown table"

version: ""

header-from: "header.md"
footer-from: ""

recursive:
  enabled: false
  path: modules

sections:
  hide: []
  show: []

content: |-
  # {{ .Header }}

  {{ if .Config.Module.Description }}{{ .Config.Module.Description }}{{ end }}

  ## Architecture

  This module creates the following AWS resources:

  {{ range .Module.Resources }}
  - {{ .Type }} ({{ .Name }})
  {{- end }}

  ## Usage

  ```hcl
  {{ include "examples/basic/main.tf" }}
  ```

  ## Requirements

  {{ .Requirements }}

  ## Providers

  {{ .Providers }}

  ## Modules

  {{ .Modules }}

  ## Resources

  {{ .Resources }}

  ## Inputs

  {{ .Inputs }}

  ## Outputs

  {{ .Outputs }}

output:
  file: "README.md"
  mode: inject
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->

output-values:
  enabled: false
  from: ""

sort:
  enabled: true
  by: name

settings:
  anchor: true
  color: true
  default: true
  description: false
  escape: true
  hide-empty: false
  html: true
  indent: 2
  lockfile: true
  read-comments: true
  required: true
  sensitive: true
  type: true
